### PR TITLE
Added the reddit auto cog, and made a few other miscellaneous changes.

### PR DESCRIPTION
**Pull request by adhityamamallan**
- Added a Reddit Auto cog to automatically post previews when someone posts a link to a Reddit post in chat
- changed gitignore, readme, config.yaml, and requirements.txt as part of minor changes
- refactored the Reddit cog to read subreddits from the config file instead of hardcoding

### CODE REVIEW

**Comment by naveen-u** [comment]
Nice, good stuff. Can we move this to the Reddit cog? Don't see the point of keeping this separate. Also, just add a line in the docs for the Reddit cog about this feature so that people can see it's there using the `help` command.

**Comment by adhityamamallan** [comment]
So, about that...
Discord bots act really weird when you have an on_message listener running alongside a command listener (I think I've told you about this before). That's why I had to separate the two.
There is, of course, an issue with the RedditAuto cog showing up in help without it having any commands; I'm looking into it.

**Comment by naveen-u** [comment]
> Discord bots act really weird when you have an on_message listener running alongside a command listener

What's the issue exactly? Can you tell me how to reproduce this? I tried moving everything to the Reddit cog and couldn't find any issues on running it locally. Also, is this issue documented somewhere?

P.S. I think the Anagram and Pokémon cogs use `on_message` along with commands and I haven't faced any issues with either of them.

**Comment by adhityamamallan** [comment]
Hmm. I remember this issue coming up when I was testing with Automated Trash Can. Lemme try it on this bot once.

**Comment by adhityamamallan** [comment]
Bruh.
It works now.
No idea what the problem could've been back then ;-;

**Pull request merged**
